version: '3'

services: 
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=atp-tour
        ports:
            - 3307:3306
        volumes:
            - "./scripts/atp-tour-db.sql:/docker-entrypoint-initdb.d/1.sql"
    
    atp-tour:
        image: lazardondo5/atp-tour
        container_name: atp-tour
        restart: on-failure
        depends_on:
            - mysql
        ports:
            - 8080:8080
        environment:
            - SPRING_PROFILES_ACTIVE = docker
            
    atp-tour-angular:
        image: lazardondo5/atp-tour-angular
        container_name: atp-tour-angular
        ports:
            - 4200:4200
